### ISSUE TITLE
Why is there no different android especially huawei for amiibo. 

### ISSUE THREAD

**Issue by mrxrnzl** [TeamJCD/JoyConDroid#51]
I love the app it works fine on my Huawei Nova 5T
The only function that will work to me is the amiibo nfc, but can you please tell me when you can work it out if you have patreon i could shell out so that this will be implemented to my phone. Need a bad assistance for this

**Comment by wsdouifhwiosdfj** [comment]
you cant use the amiibo in a non samsung cellphone and its not the app's fault, joycondroid to transfer the amiibo info to the switch needs a thing called "HID MTU value", samsung's phones with android 9 or 10 by default have it while other companies's stock android 9 or 10 doesnt have it, its not a app issue, either get a custom rom or buy a samsung
