### ISSUE TITLE
Can't connect to Switch after updating to 12.0.

### ISSUE THREAD

**Issue by 8cean** [TeamJCD/JoyConDroid#55]
Can't connect to Switch after updating to 12.0.

**Comment by dtrunk90** [comment]
Update your App to the latest version

**Comment by 8cean** [comment]
But I already update it to the latest(1.0.90.1).

**Comment by dtrunk90** [comment]
Ok then pls hold on until it is patched. Join the discord server if you want to be up-to-date.

**Comment by 8cean** [comment]
How much time will it cost? I can't open the Discord. Or will you please send the up-to-date to me by e-mail(longhaic@qq.com)?Thanks.

**Comment by M4th3wIsntHere** [comment]
theres no current ETA for the update, and no one will send you an email, please join the discord to stay tuned about the update https://discord.gg/Tn9CudzQcZ

**Comment by dtrunk90** [comment]
I'm just a supporter. There's no ETA.

**Comment by 8cean** [comment]
I cound not get to the discord because I'm in mainland.Thanks anyway.

**Comment by Venryx** [comment]
This thread appears to be about the same issue described here: https://github.com/YouTubePlays/JoyConDroid/issues/57

(May be worth closing one or the other, since their root issue is the same.)

**Comment by dtrunk90** [comment]
Root is required since firmware 12.0.0. Closing this.
