### ISSUE TITLE
Amiibo doesn't function, when you try to use it, controller disconect 

### ISSUE THREAD

**Issue by Aristeas05** [TeamJCD/JoyConDroid#57]

**Comment by M4th3wIsntHere** [comment]
lower the packet rate in the app settings

**Comment by radjwahassen** [comment]
The update here connects but cant read amiboos how doe i fix it

**Comment by Aristeas05** [comment]
> lower the packet rate in the app settings

I tried that way, but still disconnecting

**Comment by M4th3wIsntHere** [comment]
turn off the wifi on phone and try again

**Comment by Aristeas05** [comment]
> turn off the wifi on phone and try again

Still disconnect when it request the amiibo for a 2nd time, saying "cotroller disconnected"

**Comment by radjwahassen** [comment]
Its still not working i try evryrhing

**Comment by M4th3wIsntHere** [comment]
> Still disconnect when it request the amiibo for a 2nd time, saying "cotroller disconnected"

what phone are you using

**Comment by Aristeas05** [comment]
> > Still disconnect when it request the amiibo for a 2nd time, saying "cotroller disconnected"
> 
> what phone are you using

Samsung Galaxy A71

**Comment by M4th3wIsntHere** [comment]
try with the rigth con and a physical left con

**Comment by Aristeas05** [comment]
> try with the rigth con and a physical left 
Rigth Joy Disconnects or process fails when NS claims for a 2nd scan of amiibo

**Comment by M4th3wIsntHere** [comment]
are you using a .bin amiibo file?

**Comment by Aristeas05** [comment]
> are you using a .bin amiibo file?

Yep. I tried with different bin files

**Comment by M4th3wIsntHere** [comment]
are you REALLY sure its a .bin file? if yes, pre-set the amiibo to be scanned in the app settings

**Comment by Aristeas05** [comment]
> are you REALLY sure its a .bin file? if yes, pre-set the amiibo to be scanned in the app settings

Yes. And I did that. I tried with preset and without that. I found them in a G-Drive link, in a reddit post.

**Comment by M4th3wIsntHere** [comment]
reboot the phone and the switch, and try again, with the right joycon and a physical left joycon

**Comment by Aristeas05** [comment]
> reboot the phone and the switch, and try again, with the right joycon and a physical left joycon

Tried this. Still have the same problem

**Comment by M4th3wIsntHere** [comment]
well, then you'll have to wait until the next patch, the alpha version is very unstable and you've tried everything possible, theres no need to open an issue about it, YTP is already aware of these connection issues

**Comment by M4th3wIsntHere** [comment]
join our discord server to be up-to-date about when the update comes https://discord.gg/Tn9CudzQcZ

**Comment by radjwahassen** [comment]
I used the latest update for joycon but still disconect when it read a amibo .evrything else works .how can i fix this i use samsung 9 plus

**Comment by zimeau** [comment]
same problem here. when I read an amibo, joycon disconnect with the latest joycon update and with .bin file which worked very well before the switch 12.0 update.

**Comment by M4th3wIsntHere** [comment]
use a physical left joycon and joycondroid's right joycon and then try to scan again

**Comment by radjwahassen** [comment]
It wont connect anymore everytime it says not conected 😪

**Comment by M4th3wIsntHere** [comment]
did you pair to the switch BEFORE 12.0 came out?

**Comment by M4th3wIsntHere** [comment]
i also forgot to mention that only devices that were previously connected to the switch work, and if you cleared all your paired controllers, rip, you cant connect anymore

**Comment by zimeau** [comment]
> 
> 
> use a physical left joycon and joycondroid's right joycon and then try to scan again

it works for me :) thanks!

**Comment by radjwahassen** [comment]
Yes i paired and after the update from joycon here it works now nothing works he says something with bleutoorh discovery

**Comment by M4th3wIsntHere** [comment]
fix your english, i couldnt understand 1 word of what you said

**Comment by radjwahassen** [comment]
When i connect with switch lite he sayd bleutooth discovery problem

**Comment by M4th3wIsntHere** [comment]
uhm, could you show me a picture?

**Comment by radjwahassen** [comment]
![Screenshot_20210414-143658_Settings](https://user-images.githubusercontent.com/82201365/114711308-15d16400-9d2f-11eb-944a-b85822d95be2.jpg)
Now it says cant connect after 10 times trying the buttons wont work anymore to connect

**Comment by radjwahassen** [comment]
![Uploading Screenshot_20210414-143940_Joy-Con Droid.jpg…]()

**Comment by radjwahassen** [comment]
![Screenshot_20210414-143940_Joy-Con Droid](https://user-images.githubusercontent.com/82201365/114728667-95672f00-9d3f-11eb-92e1-72c90bed953e.jpg)

**Comment by radjwahassen** [comment]
Above says mistake at bluetooth discovery

**Comment by M4th3wIsntHere** [comment]
restart your phone and try again, also, you are planning to use amiibos, right? then connect a PHYSICAL left joycon and joycondroid's right joycon

**Comment by radjwahassen** [comment]
I did all of that still this problem with the joycon andriod app.it wont conect anymore 100 times it says connect but he dont connect to my switch

**Comment by M4th3wIsntHere** [comment]
then, i guess you'll have to wait until the patch comes out

**Comment by radjwahassen** [comment]
Thank you for youre help i wait for the new patch hope soon

**Comment by Venryx** [comment]
I just wanted to mention that I successfully got NXBT connecting to my 12.0.0 Switch using an XUbuntu VM running on Windows. Once the simulated controller connects (can take a few tries), I'm then able to use my PC's keyboard to play Super Smash Bros Ultimate without disconnects.

I put together a set of instructions here: https://github.com/Venryx/switch-resources/blob/master/NXBT.md
