### ISSUE TITLE
Can't pair to Nintendo Switch? 

### ISSUE THREAD

**Issue by TheGameChnger** [TeamJCD/JoyConDroid#58]
![Screenshot_20210414-141642_Joy-Con Droid](https://user-images.githubusercontent.com/82523378/114726420-4b794b80-9d35-11eb-85a4-3abff72ab97d.jpg)

This pops up after I select okay to being visible for 60 seconds. Unable to connect to the console because of this.

**Comment by M4th3wIsntHere** [comment]
are you on the change grip and order screen of the switch?

**Comment by TheGameChnger** [comment]
Hello,

Yes, on the correct screen with the left controller connected.

I open the app, select right joycon, then I select ok to being visible for 60 seconds. Nothing else happens until I press the onscreen sync button which then makes the pairing error pop up.

**Comment by M4th3wIsntHere** [comment]
> I open the app, select right joycon, then I select ok to being visible for 60 seconds. Nothing else happens until I press the onscreen sync button which then makes the pairing error pop up.

yes because you NEED to press the survey button, this way the app can find the switch, but i've seen 1 other person with the issue, they couldnt solve it, so ig you'll also have to wait until the update
