### ISSUE TITLE
incorrect key or passkey ( while connecting )

### ISSUE THREAD

**Issue by YiruTime** [TeamJCD/JoyConDroid#61]
![Screenshot_20210814-235318__01](https://user-images.githubusercontent.com/33845792/129462375-30e97802-0137-44ea-9f1d-b0f6270c555e.jpg)

I have installed it all the way. But somehow it does not accept it.

I guess its my switch cuz its on version 12.1.0

**Comment by dtrunk90** [comment]
Try to clear your paired bluetooth devices. Is your android device rooted? Take a look at https://joycon.gitbook.io/joycondroid/ for a full guide and FAQ.

**Comment by YiruTime** [comment]
I have cleared it and yes my device has been rooted. I also followed the whole guide and tried to connect in the grip/order menu and i also tried the back button trick. It still has the same outcome.

**Comment by Matrix64** [comment]
here with the same problem(1.0.90.8)

**Comment by Borgotto** [comment]
Same error here, OxygenOS 11.0.7.1.GM21AA on a OnePlus 7 Pro
Followed the guide, used Bluetooth++, workaround didn't work either

**Comment by Cyphs** [comment]
> Same error here, OxygenOS 11.0.7.1.GM21AA on a OnePlus 7 Pro
> Followed the guide, used Bluetooth++, workaround didn't work either

Try crDroid 6 (android 10). It doesn't work in OxygenOS and the newer ROMs
