### ISSUE TITLE
 Connect issues

### ISSUE THREAD

**Issue by Bentleyplayz37YT** [TeamJCD/JoyConDroid#71]
It asks to connect then it does nothing then switch discnected

**Comment by Cyphs** [comment]
Make sure your Android device is rooted and you have followed the guide. There is various information and connection workarounds listed. Please try them and make sure you have the latest release. 

https://joycondroid.gitbook.io/

**Comment by Bentleyplayz37YT** [comment]
How

**Comment by Bentleyplayz37YT** [comment]
I watched a video setup

**Comment by Bentleyplayz37YT** [comment]
I also looked at setup and still

**Comment by Bentleyplayz37YT** [comment]
I installed HID and it said i'm good

**Comment by Bentleyplayz37YT** [comment]
Uploading Screen_Recording_20240203_151958_Joy-Con Droid.mp4…

**Comment by Bentleyplayz37YT** [comment]
@Cyphs

**Comment by Bentleyplayz37YT** [comment]
https://github.com/TeamJCD/JoyConDroid/assets/158775564/52aba1c0-8599-4aa6-aa76-7cfa6aadf534

**Comment by Cyphs** [comment]
Again, it's very important you read the guide. You will not be able to use JoyCon Droid at all if your device is not rooted. Forget about outdated videos, they are no longer relevant. Bluetooth HID Profile support on your device is **not enough** to be able to use JoyCon Droid.

Root is necessary for changing your Bluetooth Class of Device. The guide explains EVERYTHING. This will not work for you if you're not willing to read and understand the guide. It's recommended for advanced users only. 

https://joycondroid.gitbook.io/

**Comment by Bentleyplayz37YT** [comment]
Speak English if you are talking about the numbers they are cknnected

**Comment by Cyphs** [comment]
I'm typing in English as far as I know. Please stop replying here, go to the JoyCon Droid Discord server for continued support, as this is an issue of user error/misunderstanding and not an issue with the app.

**Comment by dtrunk90** [comment]
Root is required.
